### ISSUE TITLE
Appendix Missing?

### ISSUE THREAD

**Issue by abdalgader-a-zz** [kepsail/SHGP#1]

**Comment by abdalgader-a-zz** [comment]
Hi there, 
This a great work and the paper is well-written. Congratulations for acceptance at Neurips2022!
Just notice the the paper does not include the appendix section (want to see the SGHP efficiency study).

Thanks!

**Comment by kepsail** [comment]
> 

Thanks for your interesst. Please see our Supplementary Material at : [OpenReview](https://openreview.net/forum?id=fBU4qsM6Fkf)

**Comment by kepsail** [comment]
Now we have updated the paper to include Appendix in the main PDF. Please see our [OpenReview](https://openreview.net/forum?id=fBU4qsM6Fkf) page.
