### ISSUE TITLE
About Data Preprocessor

### ISSUE THREAD

**Issue by xp561** [kepsail/SHGP#2]
Dear author,
         I'm trying to apply SHGP to other datasets and find out that because there are no data preprocessors I can't apply "shgp" to other datasets. So, would u please update the data preprocessing program or related documents? Thanks very much.

**Comment by kepsail** [comment]
Thanks for your interest. Please see the data preprocessing resources at OneDrive cloud drive: https://tinyurl.com/tkde-hgcn.
